### ISSUE TITLE
Long answers are chomped

### ISSUE THREAD

**Issue by dennislapchenko** [abhagsain/ai-cli#12]
Firstly - bigup for this tool. its incredible how useful and wide-reaching it is. platform/ language/cli/iam roles ... everything. 🙏 

But long answers are chomped:
<img width="242" alt="TY SAMY LUCHSHY 2022-11-28 5 PM-00-56" src="https://user-images.githubusercontent.com/17194644/204249454-dacc07c4-7814-4534-b0be-97528f5d7876.png">

I guess initially you might've not thought about such long responses, but now it seems its a killer tool that can answer a lot more!

**Comment by abhagsain** [comment]
Hey, @dennislapchenko 
Yes, we didn't think about longer responses so currently, there's a limit on the number of tokens generated. 
Also if you're generating `terraform`, wouldn't [Github Copilot ](https://github.com/features/copilot) be an ideal tool?

**Comment by dennislapchenko** [comment]
hey @abhagsain 
perhaps! have not seen Copilot in action yet. might check it out, as pretty impressed by this utility ☺️
on a side note, interesting response:
<img width="174" alt="TY SAMY LUCHSHY 2022-12-05 4 PM-39-09" src="https://user-images.githubusercontent.com/17194644/205604884-7cea43c9-ac42-42cd-ad77-e44f762d277e.png">

**Comment by abhagsain** [comment]
> hey @abhagsain perhaps! have not seen Copilot in action yet. might check it out, as pretty impressed by this utility ☺️ on a side note, interesting response: <img alt="TY SAMY LUCHSHY 2022-12-05 4 PM-39-09" width="174" src="https://user-images.githubusercontent.com/17194644/205604884-7cea43c9-ac42-42cd-ad77-e44f762d277e.png">

Yeah, currently it only sends CLI-related responses. 
I'm closing this issue then.
