### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by wll8** [abhagsain/ai-cli#20]
![image](https://user-images.githubusercontent.com/28223260/206627384-94619c2d-e5a1-485b-8e40-b7bc8eb2e1d2.png)

**Comment by wll8** [comment]
``` sh
C:\Users\win>ai --version
@abhagsain/ai-cli/1.2.2 win32-x64 node-v14.15.5
```

**Comment by abhagsain** [comment]
@wll8  Can you please check that you have a config at `~/.config/ai/config.json`?

**Comment by wll8** [comment]
``` sh
C:\Users\win>type C:\Users\win\AppData\Local\ai\config.json
{"model":"text-davinci-003"}
```

**Comment by wll8** [comment]
I've tested adding quotes before this, and I'll test it again. I understand that quotes are not necessary when no spaces or special characters are included.

``` sh
C:\Users\win>ai ask "hello"
... !
    Error: Request failed with status code 400

C:\Users\win>ai ask "Check running containers"
... !
    Error: Request failed with status code 400

C:\Users\win>

```

**Comment by abhagsain** [comment]
@wll8 That's strange. Can you please run this `curl` with your API keys? Not sure if it's an issue with OpenAI's API or the CLI. 
If this passes, I'll publish a new version that shows errors to stdout.
```
curl https://api.openai.com/v1/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
  "model": "text-davinci-003",
  "prompt": "Say hello in language\nSpanish: Hola\nFrench:",
  "temperature": 0.7,
  "max_tokens": 256,
  "top_p": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0
}'
```

**Comment by abhagsain** [comment]
Also, please make sure that you have added payment info to your account.

**Comment by wll8** [comment]
I don't know if the account needs a balance, but my account can be used normally on the `https://chat.openai.com/chat` page.

``` sh
$ curl https://api.openai.com/v1/completions \ 
Drf9MhRk6Q7e>   -H "Content-Type: application/json" \
>   -H "Authorization: Bearer ******" \
>   -d '{
>   "model": "text-davinci-003",
>   "prompt": "Say hello in language\nSpanish: Hola\nFrench:",
>   "temperature": 0.7,
>   "max_tokens": 256,
>   "top_p": 1,
>   "frequency_penalty": 0,
>   "presence_penalty": 0
> }'
{"id":"cmpl-6LQMHo4xph0Wj6SPA0kb0XqmgXxd8","object":"text_completion","created":1670564229,"model":"text-davinci-003","choices":[{"text":" Bonjour","index":0,"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":12,"completion_tokens":3,"total_tokens":15}}
```

![image](https://user-images.githubusercontent.com/28223260/206632874-2689064f-c1b7-4360-b225-83040cef0d6e.png)


![image](https://user-images.githubusercontent.com/28223260/206632517-770f09b4-571a-4b82-8236-194c2c6eee6e.png)

**Comment by abhagsain** [comment]
It seems that there's a bug in the code. Let me try to reproduce it on my end.

**Comment by abhagsain** [comment]
@wll8 Found the issue, releasing the fix in a few minutes.

**Comment by wll8** [comment]
Is this the fix?

![image](https://user-images.githubusercontent.com/28223260/206636469-530a4300-d5c2-49d4-b3d8-a219edbac5e8.png)

**Comment by abhagsain** [comment]
> Is this the fix?
> 
> ![image](https://user-images.githubusercontent.com/28223260/206636469-530a4300-d5c2-49d4-b3d8-a219edbac5e8.png)

Yes, that's the issue but the default model getting saved should have the `name` key. (see at the top) I'm committing my changes.

**Comment by abhagsain** [comment]
@wll8 Fixed the issue, please install the latest version (v1.2.3)
