### ISSUE TITLE
GPT-4 ?

### ISSUE THREAD

**Issue by endrureza** [abhagsain/ai-cli#50]
does this library support gpt 4 ?

**Comment by KrustyHack** [comment]
Ay,

Not at the moment because it use completion, not chat API endpoints.

**Comment by abhagsain** [comment]
@endrureza @KrustyHack 

We migrated to the Chat endpoint recently, so you can switch to GPT4 now with the `ai model.` Please upgrade to the latest version.

Closing this issue.
