### ISSUE TITLE
Default model text-davinci-003 deprecated

### ISSUE THREAD

**Issue by deivid11** [abhagsain/ai-cli#52]
Error: {"message":"The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations","type":"invalid_request_error","param":null,"code":"model_not_found"}

The new models should be added to the ai model menu.

**Comment by deivid11** [comment]
I've tried a quick fix adding the gpt-3.5-turbo but not working. 

    Error: {"message":"This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?","type":"invalid_request_error","param":"model","code":null}

I think it needs a bigger refactor. @abhagsain tell me if you can make the compatibility fixes please, if not I could spend some time  to fix it and to send you a pull request later. I really love this utility.

**Comment by deivid11** [comment]
Well, the fastest solution I found was making a Custom GPT xD, so you are welcome to use it. Here is the link for Chat GPT users.
I've used the prompts used on this project, so it should behave similar.
https://chat.openai.com/g/g-qdIxnXxnX-ai-cli-for-linux

**Comment by re4388** [comment]
Good work deivid11, but to your work requiring chatGptPlus
`Sign up for ChatGPT Plus to chat with AI CLI for Linux`

**Comment by abhagsain** [comment]
> I've tried a quick fix adding the gpt-3.5-turbo but not working.
> 
> ```
> Error: {"message":"This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?","type":"invalid_request_error","param":"model","code":null}
> ```
> 
> I think it needs a bigger refactor. @abhagsain tell me if you can make the compatibility fixes please, if not I could spend some time to fix it and to send you a pull request later. I really love this utility.

Hi, deivid11
I'll see if I can make a quick fix this weekend or early next week.

**Comment by deivid11** [comment]
> Good work deivid11, but to your work requiring chatGptPlus `Sign up for ChatGPT Plus to chat with AI CLI for Linux`

O

> Good work deivid11, but to your work requiring chatGptPlus `Sign up for ChatGPT Plus to chat with AI CLI for Linux`

Ohh that's ture, GPTs are only available for ChatGTP plus users

**Comment by abhagsain** [comment]
Hi, @deivid11 
Sorry, Didn't get the time. I'm busy with some other work. Let me know if you want to pick this up. 
Thank you

**Comment by abhagsain** [comment]
OpenAI's older model is deprecated. The task is to refactor the code to support new models and update the package.
Thanks :)
