### ISSUE TITLE
Error: Request failed with status code 429

### ISSUE THREAD

**Issue by planetoid** [abhagsain/ai-cli#6]
When I enter the first command `ai ask "Check process running on port xxx"`, it show the error message `Error: Request failed with status code 429`. My account are currently on the free trial.

I have no idea how to solve this issue. Any help will be appreciate.

**Comment by abhagsain** [comment]
Hey, I added the URL to easily access the GitHub repo (as the URL is easy to remember) when shared on social media platforms but there's no UI as such to try out the CLI. You'd need to install it yourself `npm i @abhagsain/ai-cli -g` 

So sorry for the misleading body copy. I have reverted it https://github.com/abhagsain/ai-cli/commit/f2726b2bf75fdb9712a569570f951e33f2d8743d

**Comment by abhagsain** [comment]
Hey, @planetoid did it return any results even once or you're getting `429` from the start?
Just a guess but you might have to add payment information to your account. 
Don't worry you won't be charged right away, it's pay-as-you-use model but please check out the [pricing page](https://openai.com/api/pricing/) for more

**Comment by screwgoth** [comment]
Getting the exact same error as @planetoid

**Comment by abhagsain** [comment]
> 

Have you added Payment Information? That's the only issues I can think of 
There's rate limit on number of tokens `(150K tokens/minute)` which is more than enough. The tokens for our prompt would be `~1K`
https://help.openai.com/en/articles/5955604-how-can-i-solve-429-too-many-requests-errors 
https://help.openai.com/en/articles/5955598-is-api-usage-subject-to-any-rate-limits

**Comment by ciudilo** [comment]
I have added payment information and still getting 429

**Comment by rouseguy** [comment]
I had the same issue. Added payment to OpenAI account and voila! the commands work.

**Comment by abhagsain** [comment]
> I had the same issue. Added payment to OpenAI account and voila! the commands work.

So this is the solution @planetoid @screwgoth :)
Thanks for sharing @rouseguy

**Comment by abhagsain** [comment]
> I had the same issue. Added payment to OpenAI account and voila! the commands work.

This seems like the solution so closing this.
